version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    groups:
      minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
