auth:
    password: $2a$12$EHitFaZeRKOg1CFneyIhl./Mij2DiVgkDRzjZDV3lFJkR22n4WvEm
    username: admin
cache:
    enabled: true
    maxsize: 1000
    ttl: 5m
    type: memory
jwt:
    secret: bfspo%R&^5KXmCamSfC#b3XCKuCwbSfmPA0OWNxfBPNywW#sxWv9qWMRoy#M4vn0
kubernetes:
    insecure: false
    kubeconfig: ""
log:
    format: console
    level: info
server:
    host: 0.0.0.0
    port: "8080"
